#pragma once

#include <windows.h>
#include <winioctl.h>
#include <sstream>

/*
* IOCTL for STARLIGHT GUI KERNEL DRIVER (SKT64)
*/
#define IOCTL_PROHIBIT_CREATEPROCESS       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x400, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROHIBIT_CREATEPROCESS     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x401, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROHIBIT_CREATEFILE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x402, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROHIBIT_CREATEFILE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x403, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROHIBIT_LOADDRIVER          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x404, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROHIBIT_LOADDRIVER        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x405, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROHIBIT_MODIFY_REGISTRY     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x406, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROHIBIT_MODIFY_REGISTRY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x407, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROTECT_DISK                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x408, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROTECT_DISK               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x409, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROHIBIT_UNLOADDRIVER        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x410, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROHIBIT_UNLOADDRIVER      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x411, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_OBCALLBACK           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x414, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENABLE_OBCALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x415, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_DSE                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x416, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENABLE_DSE                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x417, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SHUTDOWN                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x418, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REBOOT                       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x419, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_REBOOT                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x420, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_BLUESCREEN                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x421, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_CMPCALLBACK          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x426, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENABLE_CMPCALLBACK           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x427, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENABLE_SCAN_EPT_HOOK         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x430, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_SCAN_EPT_HOOK        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x431, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENABLE_LKD                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x434, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_LKD                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x435, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_DISABLE_PATCHGUARD_EFI       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x500, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_PATCHGUARD_BIOS      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x501, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DISABLE_PATCHGUARD_DYNAMIC   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x502, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ENUM_DRIVERS		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_MINIFILTER              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SCAN_MSRHOOK                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_FILE                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_EXCALLBACK              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_SYTSTEMTHREAD           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_IRP_HOOK                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_CREATE_THREAD_NOTIFY    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_CREATE_PROCESS_NOTIFY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_OB_PROCESS_CALLBACK     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_OB_THREAD_CALLBACK      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_OB_DESKTOP_CALLBACK     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_LOADIMAGE_NOTIFY        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_REGISTRY_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_BUGCHECK_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x815, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_BUGCHECKREASON_CALLBACK CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_SHUTDOWN_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x817, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_LASTSHUTDOWN_NOTIFY     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x818, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_FS_NOTIFY               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x819, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_POWERSETTING_NOTIFY     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_COALESCING_NOTIFY       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PRIORIRY_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x822, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_DBGPRINT_CALLBACK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x823, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_NMI_CALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x824, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_OBJECT_TYPE_TABLE       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x825, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_IO_TIMER                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x826, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_IDT                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x827, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_SSDT                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x828, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_WFPCALLOUT              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x829, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS_THREAD          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_GDT                     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x831, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_UNLOADED_DRIVERS        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x832, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_DRIVER_MAJORFUNCTIONS   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x833, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_SSSDT                   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x834, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x835, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_HALPRIVATEDISPATCHTABLE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x836, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_HALDISPATCHTABLE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x837, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PLUGPLAY_NOTIFY         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x838, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_EMP_CALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x839, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PIDDBCACHE_TABLE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x840, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NTFS_PARSER_ENUM_FILE2       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x843, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_FILE2                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x844, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_FILE_IRP               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x845, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS_THREAD_CIDTABLE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x848, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PHYSICAL_DISK           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x849, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_HOT_KEY                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x850, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_KERNELCALLBACKTABLE     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x851, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS_EXIST_HANDLE    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x852, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS_MODULE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x853, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_PROCESS_VAD             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x854, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_STANDARD_FILTER         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x855, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_TERMINATE_PROCESS		       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNLOAD_DRIVER 	           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HIDE_DRIVER		           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_TERMINATE_PROCESS      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SUSPEND_PROCESS              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RESUME_PROCESS               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HIDE_PROCESS                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_PPL                      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_CRITICAL_PROCESS         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETE_FILE                  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x911, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_DELETE_FILE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x912, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DELETE_FILE_UNICODE          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x913, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_DELETE_UNICODE         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x914, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOCK_FILE                    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x915, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOCK_FILE_UNICODE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x916, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_MINIFILTER            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x917, METHOD_BUFFERED, FILE_ANY_ACCESS) // Unused
#define IOCTL_REMOVE_EXCALLBACK            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x918, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TERMINATE_THREAD             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x919, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_NOTIFY                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x920, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_MSRHOOK               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x921, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_SSDTHOOK              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x922, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SUSPEND_THREAD               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x925, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RESUME_THREAD                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x926, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FORCE_TERMINATE_THREAD       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x927, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SHELLCODE_INJECT_DLL         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x933, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_MINIFILTER2           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x938, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNHOOK_SSDT_INLINEHOOK       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x942, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNHOOK_SSSDT                 CTL_CODE(FILE_DEVICE_UNKNOWN, 0x943, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_PIDDBCACHE            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x944, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MODIFY_PROCESS_TOKEN         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x947, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CRASH_SYSTEM_SET_COLOR       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x948, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_NTFS_COPY_FILE               CTL_CODE(FILE_DEVICE_UNKNOWN, 0x952, METHOD_BUFFERED, FILE_ANY_ACCESS)

/*
* PPL levels
*/
#define PPL_WinSystem 0x71
#define PPL_WinTcb 0x61
#define PPL_Windows 0x51
#define PPL_Lsa 0x41
#define PPL_Antimalware 0x31
#define PPL_Codegen 0x21
#define PPL_Authenticode 0x11
#define PPL_None 0x00

typedef struct _DATA_INFO_
{
    HANDLE handledata1;
    HANDLE handledata2;
    HANDLE handledata3;
    HANDLE handledata4;
    PVOID pvoidaddressdata1;
    PVOID pvoidaddressdata2;
    PVOID pvoidaddressdata3;
    PVOID pvoidaddressdata4;
    ULONG ulongdata1;
    ULONG ulongdata2;
    ULONG ulongdata3;
    ULONG ulongdata4;
    ULONG64 ulong64data1;
    ULONG64 ulong64data2;
    ULONG64 ulong64data3;
    ULONG64 ulong64data4;
    PUCHAR puchardata1;
    char Module[MAX_PATH];
    char Module1[MAX_PATH];
    WCHAR wcstr[MAX_PATH];
    WCHAR wcstr1[MAX_PATH];
    WCHAR wcstr2[MAX_PATH];
    WCHAR wcstr3[MAX_PATH];
}DATA_INFO, * PDATA_INFO;

typedef struct _DRIVER_INFO_
{
    ULONG_PTR nLoadOrder;
    ULONG_PTR nBase;
    ULONG_PTR nSize;
    ULONG_PTR nDriverObject;
    char szDriverPath[MAX_PATH];
    char szDriverName[MAX_PATH];
} DRIVER_INFO, * PDRIVER_INFO;

typedef struct _ALL_DRIVERS_
{
    ULONG nCnt;
    DRIVER_INFO Drivers[1];
} ALL_DRIVERS, * PALL_DRIVERS;

typedef enum _ENUM_FILTER_TYPE
{
    ft_Unknown,
    ft_File,
    ft_Disk,
    ft_Volume,
    ft_Keyboard,
    ft_Mouse,
    ft_I8042prt,
    ft_Tcpip,
    ft_Ndis,
    ft_PnpManager,
    ft_Tdx,
    ft_Raw
} ENUM_FILTER_TYPE, * PENUM_FILTER_TYPE;

typedef enum _KTHREAD_STATE
{
    ThreadState_Initialized,
    ThreadState_Ready,
    ThreadState_Running,
    ThreadState_Standby,
    ThreadState_Terminated,
    ThreadState_Waiting,
    ThreadState_Transition,
    ThreadState_DeferredReady,
    ThreadState_GateWait
} KTHREAD_STATE, * PKTHREAD_STATE;

typedef enum _MFT_RECORD_FLAGS {
    MFT_RECORD_FLAG_NONE = 0x0000,
    MFT_RECORD_FLAG_FILE = 0x0001,
    MFT_RECORD_FLAG_DIRECTORY = 0x0003,
    MFT_RECORD_FLAG_UNKNOWN = 0x0100
} MFT_RECORD_FLAGS;

typedef enum _TOKEN_MODIFY_TYPE
{
    MToken_System,
    MToken_TrustedInstaller,
    MToken_DWM,
    MToken_UMDF
}TOKEN_MODIFY_TYPE, * PTOKEN_MODIFY_TYPE;